version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: environment_db_container
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: env_hub_backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: env_hub_frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  db_data:
